Sudoku/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', TemplateView.as_view(template_name='code/home.html'), name='home'),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^code/', include('code.urls', namespace="code")),
	url(r'^admin/', include(admin.site.urls)),
)

code/urls.py
from django.conf.urls import patterns, url
from code import views

urlpatterns = patterns('',
	url(r'^home/$', views.input_sudoku, name='input'),
	url(r'^display/$', views.display_sudoku, name='display'),
	url(r'^solution/$', views.solve_sudoku, name='solution'),
	url(r'^nosolution/$', views.no_solution, name='no_solution'),
)

code/views.py
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError, Http404
from django.shortcuts import get_object_or_404, render, render_to_response
from django.core.urlresolvers import reverse
from django.views import generic
from solution import Solution
from django.core.context_processors import csrf

def input_sudoku(request):
	c = {}
	c.update(csrf(request))
	return render_to_response('code/home.html', c)

def no_solution(request):
	return render(request, 'code/nosolution.html')

def solve_sudoku(request):
	sudoku_input = []
	for i in range(0, 81):
		input_character = request.POST[str(i)]
		if len(input_character) == 0:
			sudoku_input.append('.')
		else:
			sudoku_input.append(input_character)

	sudoku_solution = Solution(sudoku_input).return_grid()
	# Save session to display the contents of the solution of the sudoku
	# in the display_sudoku view
	# Always redirect after POST.
	request.session['sudoku_solution'] = repr(sudoku_solution)

	if not sudoku_solution:
		return HttpResponseRedirect(reverse('code:no_solution'))
	else:
		return HttpResponseRedirect(reverse('code:display'))

def display_sudoku(request):
	sudoku_solution = request.session.get('sudoku_solution', None)

	if sudoku_solution is not None:
		sudoku_solution = eval(sudoku_solution)
	else:
		return HttpResponseRedirect(reverse('code:no_solution'))

	return render(request, 'code/solution.html', {"grid":sudoku_solution})

code/templates/code/home.html
<!DOCTYPE html>
<html>
{% load extras %}
<body>
<div class="container" >
	<center><h3>Enter Sudoku [9 x 9] matrix</h3>
	<form name="sudokuInput" method="post" action="{% url 'code:solution' %}" >
	{% csrf_token %}
		<table width="30%" align="center"  cellspacing="5"  bgcolor="#FFFFFF" class="table table-bordered" >
		<tbody>                                
		{% for row in "9"|range_list %}
				<tr>
		{% with forloop.counter0 as out_counter %}
				{% for element in "9"|range_list %}
					{% with out_counter|multiply:9 as in_counter %}
					{% with in_counter|addition:forloop.counter0 as unique_id %}
					<th width="20" height="35" valign="middle" bordercolor="#000000" bgcolor="#FFFFFF" class="style2" id="cell-element{{ unique_id }}">
					<input name="{{ unique_id }}" id="{{ unique_id }}" type="number" min="1" max="9" ;" class="input-sm"/>					</th>
				  {% endwith %}
					{% endwith %}
				{% endfor %}
		  {% endwith %}				</tr>
			{% endfor %}
	  </table>
</div><br>
	<center><input type="submit" value="solve" id="submit" />
</form>
</div>
</body>
</html>

code/templates/code/nosolution.html
<!DOCTYPE html>
<html>
{% load extras %}
<body>
<div class="container">
	<h3 style='text-align: center;'>INCORRECT VALUES</h3>
	<br>
	<form action="{% url 'code:input' %}" class="text-center">
	<center>	<input type="submit" value="Reset"/>
	</form>
</div>
</body>
</html>

code/templates/code/solution.html
<!DOCTYPE html>
<html>
{% load extras %}
<body>
<div class="container">
	<center><h3>Solution</h3>
	<br>
	<table width="30%" align="center" cellspacing="5"  bordercolor="#000000" class="style1" >
	<tbody >
		{% for row in grid %}
			<tr >
			{% for element in row %}
				<td   bordercolor="#000000"  " class="style2" cellpadding="5">{{  element }}</td>
		  {% endfor %}			</tr>
		{% endfor %}
	</tbody>   
	</table>
  <form action="{% url 'code:input' %}">
	</br><center>	<input type="submit" value="Reset"/>
	</form>
</div>
{% for posted_value in nothing %}
	{{ posted_value }}
{% endfor %}
</body>
</html>